# Generated by Django 5.2.8 on 2025-11-22 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=150)),
                ('ruc', models.CharField(max_length=20, unique=True)),
                ('pais', models.CharField(max_length=50)),
                ('tipo_empresa', models.CharField(choices=[('importadora', 'Importadora'), ('exportadora', 'Exportadora'), ('mixta', 'Importadora/Exportadora')], default='mixta', max_length=20)),
                ('sitio_web', models.URLField(blank=True)),
                ('contacto_comercial', models.CharField(blank=True, max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_productor', models.CharField(choices=[('pequeno', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande')], default='pequeno', max_length=20)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('certificaciones', models.TextField(blank=True, help_text='Certificaciones: orgánico, fair trade, etc.')),
                ('capacidad_produccion_anual_ton', models.DecimalField(blank=True, decimal_places=2, help_text='Capacidad de producción anual en toneladas (opcional).', max_digits=12, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='productor', to='usuarios.usuario')),
            ],
        ),
    ]
