# Generated by Django 5.2.8 on 2025-11-22 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacioncomercial',
            name='fecha_llegada_estimada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operacioncomercial',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operacioncomercial',
            name='moneda',
            field=models.CharField(choices=[('USD', 'Dólar estadounidense'), ('EUR', 'Euro'), ('PEN', 'Sol peruano')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='operacioncomercial',
            name='pais_destino',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='operacioncomercial',
            name='precio_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto total acordado para la operación.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='operacioncomercial',
            name='puerto_destino',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='operacioncomercial',
            name='puerto_origen',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='DocumentoAduanero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('factura', 'Factura comercial'), ('packing_list', 'Packing List'), ('cert_fito', 'Certificado fitosanitario'), ('otros', 'Otros')], max_length=20)),
                ('archivo', models.FileField(upload_to='documentos_aduaneros/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='operaciones.operacioncomercial')),
            ],
        ),
    ]
