# Generated by Django 5.2.8 on 2025-11-23 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_operacioncomercial_fecha_llegada_estimada_and_more'),
        ('usuarios', '0002_empresa_productor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacioncomercial',
            name='fecha_llegada_estimada',
        ),
        migrations.RemoveField(
            model_name='operacioncomercial',
            name='fecha_salida',
        ),
        migrations.AddField(
            model_name='operacioncomercial',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operacioncomercial',
            name='productor',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, related_name='operaciones_productor', to='usuarios.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentoaduanero',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='documentoaduanero',
            name='tipo',
            field=models.CharField(choices=[('factura', 'Factura'), ('guia_remision', 'Guía de Remisión'), ('certificado_origen', 'Certificado de Origen'), ('otro', 'Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='operacioncomercial',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='operacioncomercial',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('en_transito', 'En tránsito'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='operacioncomercial',
            name='moneda',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='operacioncomercial',
            name='pais_destino',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='operacioncomercial',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operacioncomercial',
            name='puerto_destino',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='operacioncomercial',
            name='puerto_origen',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='operacioncomercial',
            name='tipo_operacion',
            field=models.CharField(choices=[('IMP', 'Importación'), ('EXP', 'Exportación')], max_length=3),
        ),
    ]
