# Generated by Django 5.2.8 on 2025-11-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('fruta', 'Fruta'), ('hortaliza', 'Hortaliza'), ('grano', 'Grano'), ('otro', 'Otro')], default='fruta', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='certificaciones',
            field=models.TextField(blank=True, help_text='Certificaciones específicas del producto.'),
        ),
        migrations.AddField(
            model_name='producto',
            name='es_perecible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('kg', 'Kilogramo'), ('ton', 'Tonelada'), ('caja', 'Caja'), ('unidad', 'Unidad')], default='kg', max_length=10),
        ),
    ]
