# Generated by Django 5.2.8 on 2025-11-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_categoria_producto_certificaciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incoterm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('obligaciones_vendedor', models.TextField(blank=True)),
                ('obligaciones_comprador', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Incoterm',
                'verbose_name_plural': 'Incoterms',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='NormaComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EXP', 'Exportación'), ('IMP', 'Importación'), ('AMB', 'Ambos')], max_length=3)),
                ('pais', models.CharField(max_length=100)),
                ('categoria_producto', models.CharField(blank=True, help_text='Opcional. Ej: Frutas, Granos, Café, etc.', max_length=100)),
                ('descripcion', models.TextField()),
                ('enlace_oficial', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Norma comercial',
                'verbose_name_plural': 'Normas comerciales',
                'ordering': ['pais', 'tipo'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='incoterms',
            field=models.ManyToManyField(blank=True, help_text='Incoterms aplicables a este producto', related_name='productos', to='productos.incoterm'),
        ),
        migrations.AddField(
            model_name='producto',
            name='normas_comerciales',
            field=models.ManyToManyField(blank=True, help_text='Normativa comercial asociada al producto', related_name='productos', to='productos.normacomercial'),
        ),
    ]
