# Generated by Django 5.2.8 on 2025-12-01 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_incoterm_normacomercial_producto_incoterms_and_more'),
        ('productos', '0003_producto_imagen'),
    ]

    operations = [
    ]
